const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.SVGPicture,
		C3.Behaviors.MoveTo,
		C3.Plugins.Text,
		C3.Plugins.Touch,
		C3.Plugins.Sprite,
		C3.Plugins.Mouse,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.SVGPicture.Exps.Width,
		C3.Plugins.SVGPicture.Exps.Height,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.SVGPicture.Acts.Destroy,
		C3.Plugins.Text.Acts.Destroy,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.SVGPicture.Acts.SetSize,
		C3.Plugins.SVGPicture.Acts.SetPos,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetSize,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.SVGPicture.Exps.X,
		C3.Plugins.SVGPicture.Exps.Y,
		C3.Plugins.SVGPicture.Acts.SetBoolInstanceVar,
		C3.Plugins.SVGPicture.Acts.SetImage,
		C3.Plugins.System.Cnds.PickByComparison,
		C3.Plugins.Text.Exps.IID,
		C3.Plugins.SVGPicture.Exps.IID,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.SVGPicture.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Cnds.CompareOpacity,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.System.Cnds.PickAll,
		C3.Plugins.SVGPicture.Acts.SetOpacity,
		C3.Plugins.SVGPicture.Cnds.CompareX,
		C3.Plugins.SVGPicture.Cnds.CompareY,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Mouse.Acts.SetCursor,
		C3.Plugins.System.Acts.GoToLayout
	];
};
self.C3_JsPropNameTable = [
	{ŞurayaTaşı: 0},
	{Kale: 0},
	{dolu: 0},
	{Kare: 0},
	{Yazı: 0},
	{Dokun: 0},
	{YazıYonerge: 0},
	{Sprite: 0},
	{Butonlar: 0},
	{Sprite2: 0},
	{Fare: 0},
	{Sprite3: 0},
	{Spr_Donutler: 0},
	{m: 0},
	{n: 0},
	{x0: 0},
	{y0: 0},
	{sayac: 0},
	{X: 0},
	{gidilbilecekkaresayisi: 0},
	{Y: 0},
	{i: 0},
	{i2: 0}
];

self.InstanceType = {
	Kale: class extends self.ISVGPictureInstance {},
	Kare: class extends self.ISVGPictureInstance {},
	Yazı: class extends self.ITextInstance {},
	Dokun: class extends self.IInstance {},
	YazıYonerge: class extends self.ITextInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Butonlar: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Fare: class extends self.IInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Spr_Donutler: class extends self.ISpriteInstance {}
}